# Generated by Django 4.1.7 on 2023-06-18 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seccion', '0002_alter_municipio_nombre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='colonia',
            name='tipo',
        ),
        migrations.AddField(
            model_name='colonia',
            name='cp',
            field=models.CharField(default='', max_length=5, verbose_name='Codigo Postal'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='colonia',
            name='tipo_de_colonia',
            field=models.CharField(default='', max_length=150, verbose_name='Tipo de Colonia'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='colonia',
            name='tipo_de_seccion',
            field=models.CharField(default='', max_length=150, verbose_name='Tipo de Seccion'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='colonia',
            name='nombre',
            field=models.CharField(max_length=150, verbose_name='Nombre de la Colonia'),
        ),
    ]
