# Generated by Django 4.1.7 on 2023-06-18 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Referente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre')),
                ('apellido_paterno', models.CharField(max_length=150, verbose_name='Apellido Paterno')),
                ('apellido_materno', models.CharField(max_length=150, verbose_name='Apellido Materno')),
                ('tipo_referente', models.CharField(choices=[('REFERENTE 1', 'REFERENTE 1'), ('REFERENTE 2', 'REFERENTE 2'), ('REFERENTE 3', 'REFERENTE 3')], max_length=150)),
            ],
            options={
                'verbose_name': 'Referente',
                'verbose_name_plural': 'Referentes',
            },
        ),
    ]
