# Generated by Django 4.1.7 on 2023-05-01 22:12

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('seccion', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comision', models.CharField(choices=[('ORGANIZACIÓN ELECTORAL Y DEFENSA DEL VOTO', 'ORGANIZACIÓN ELECTORAL Y DEFENSA DEL VOTO'), ('DIFUSIÓN', 'DIFUSIÓN'), ('FORMACIÓN POLÍTICA Y CÍRCULOS DE REFLEXIÓN Y ESTUDIO', 'FORMACIÓN POLÍTICA Y CÍRCULOS DE REFLEXIÓN Y ESTUDIO'), ('VINCULACIÓN Y PROMOCIÓN DE CAUSAS Y MOVIMIENTOS POPULARES Y SOCIALES O LABORALES CULTURALES', 'VINCULACIÓN Y PROMOCIÓN DE CAUSAS Y MOVIMIENTOS POPULARES Y SOCIALES O LABORALES CULTURALES'), ('SALUD', 'SALUD'), ('DEPORTIVAS', 'DEPORTIVAS')], max_length=150)),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre')),
                ('apellido_paterno', models.CharField(max_length=150, verbose_name='Apellido Paterno')),
                ('apellido_materno', models.CharField(max_length=150, verbose_name='Apellido Materno')),
                ('calle', models.CharField(max_length=150, verbose_name='Calle')),
                ('numero_exterior', models.CharField(max_length=25, verbose_name='Numero Exterior')),
                ('numero_interior', models.CharField(blank=True, max_length=25, null=True, verbose_name='Numero Interior')),
                ('telefono', models.CharField(max_length=15, verbose_name='Telefono')),
                ('codigo_postal', models.CharField(max_length=5, verbose_name='Codigo Postal')),
                ('clave_electoral', models.CharField(max_length=18, unique=True, validators=[django.core.validators.RegexValidator('^[a-zA-Z0-9 ]*$', 'SOLO SE PERMITEN NUMEROS Y LETRAS'), django.core.validators.MaxLengthValidator(18, message='ESTE CAMPO DEBE TENER EXACTAMENTE 18 CARACTERES.')])),
                ('curp', models.CharField(max_length=18, unique=True, validators=[django.core.validators.RegexValidator('^[a-zA-Z0-9 ]*$', 'SOLO SE PERMITEN NUMEROS Y LETRAS'), django.core.validators.MaxLengthValidator(18, message='ESTE CAMPO DEBE TENER EXACTAMENTE 18 CARACTERES.')])),
                ('correo_electronico', models.EmailField(blank=True, max_length=150, null=True, verbose_name='Correo Electronico')),
                ('facebook', models.CharField(blank=True, max_length=150, null=True, verbose_name='Facebook')),
                ('twitter', models.CharField(blank=True, max_length=150, null=True, verbose_name='Twitter')),
                ('colonia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personas_colonia', to='seccion.seccion', verbose_name='Colonia')),
                ('seccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personas_seccion', to='seccion.seccion', verbose_name='Seccion')),
            ],
            options={
                'verbose_name': 'Persona',
                'verbose_name_plural': 'Personas',
            },
        ),
    ]
