# Generated by Django 4.1.7 on 2023-06-18 18:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seccion', '0004_alter_colonia_cp'),
        ('persona', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='colonia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personas_colonia', to='seccion.colonia', verbose_name='Colonia'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='comision',
            field=models.CharField(choices=[('REFERENTE', 'REFERENTE'), ('ENLACE', 'ENLACE'), ('SIMPATIZANTE', 'SIMPATIZANTE'), ('MILITANTE', 'MILITANTE'), ('DEFENSOR DEL VOTO', 'DEFENSOR DEL VOTO')], max_length=150),
        ),
    ]
