# Generated by Django 4.1.7 on 2023-06-27 06:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('referente', '0001_initial'),
        ('persona', '0002_alter_persona_colonia_alter_persona_comision'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='referente_1',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='referente.referente', verbose_name='Referente'),
            preserve_default=False,
        ),
    ]
