# Generated by Django 4.1.7 on 2023-06-27 06:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('referente', '0001_initial'),
        ('persona', '0003_persona_referente_1'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='referente_2',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='personas_referente_2', to='referente.referente', verbose_name='Referente 2'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='persona',
            name='referente_1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personas_referente_1', to='referente.referente', verbose_name='Referente 1'),
        ),
    ]
