# Generated by Django 4.1.7 on 2023-06-27 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0004_persona_referente_2_alter_persona_referente_1'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='referente_3',
            field=models.CharField(default='Referente 3', max_length=150, verbose_name='Referente 3'),
            preserve_default=False,
        ),
    ]
