# Generated by Django 4.1.7 on 2023-06-27 07:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('folio', '0002_alter_folio_numero'),
        ('persona', '0005_persona_referente_3'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='folio',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='folio.folio', verbose_name='Folio'),
            preserve_default=False,
        ),
    ]
