# Generated by Django 4.1.7 on 2023-06-27 07:16

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('referente', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Folio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField(help_text='Ingresa un número entre 5 y 7 dígitos', unique=True, validators=[django.core.validators.MinLengthValidator(5, 'El número debe tener al menos 5 dígitos'), django.core.validators.MaxLengthValidator(7, 'El número no puede tener más de 7 dígitos')], verbose_name='Numero de Folio')),
                ('referente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='referente.referente', verbose_name='Referente')),
            ],
            options={
                'verbose_name': 'Folio',
                'verbose_name_plural': 'Folios',
            },
        ),
    ]
